# Generated by Django 4.2.1 on 2023-05-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResizeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Resize/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
